POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "driver", "password": "Pass1234!", "email": "driver@gmail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "driver", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token fce7305fdc37ca8dd750e3b7231f8425f048210b
